// AUTOGENERATED by generate_theme.py
// Source: dark-purple-3840x2160-17330.png
// Edit this file directly or re-run the script.
import QtQuick

QtObject {
    readonly property color bgDark:      "#130d2f"
    readonly property color bgBar:       "#7f130d2f"
    readonly property color bgPopup:     "#19113d"
    readonly property color bgPopupBlur: "#b2130d2f"
    readonly property color text:        "#c3c2c6"
    readonly property color textBright:  "#f7f7f7"
    readonly property color textMuted:   "#8b7fbc"
    readonly property color border:      "#66433775"
    readonly property color hover:       "#6553b6"
    readonly property color active:      "#b0a6dd"
    readonly property color activeText:  "#252427"
    readonly property color empty:       "#403379"
    readonly property color warn:        "#d09caa"
    readonly property color green:       "#78c293"

    // Wallpaper picker semantic aliases
    readonly property color base:     "#130d2f"
    readonly property color mantle:   "#19113d"
    readonly property color surface1: "#403379"
    readonly property color surface2: "#6553b6"

    readonly property int barHeight:    50
    readonly property int moduleRadius: 8
    readonly property int moduleHeight: 16
    readonly property int popupRadius:  12
    readonly property int popupPad:     12
    readonly property int popupWidth:   320

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
}
