// AUTOGENERATED by generate_theme.py
// Source: 04. Synth Wave.jpg
// Edit this file directly or re-run the script.
import QtQuick

QtObject {
    readonly property color bgDark:      "#31112d"
    readonly property color bgBar:       "#7f31112d"
    readonly property color bgPopup:     "#40163a"
    readonly property color bgPopupBlur: "#b231112d"
    readonly property color text:        "#c6c2c5"
    readonly property color textBright:  "#f7f7f7"
    readonly property color textMuted:   "#bc7fb4"
    readonly property color border:      "#6675376d"
    readonly property color hover:       "#b653a8"
    readonly property color active:      "#dda6d5"
    readonly property color activeText:  "#272427"
    readonly property color empty:       "#793370"
    readonly property color warn:        "#d09caa"
    readonly property color green:       "#78c293"

    // Wallpaper picker semantic aliases
    readonly property color base:     "#31112d"
    readonly property color mantle:   "#40163a"
    readonly property color surface1: "#793370"
    readonly property color surface2: "#b653a8"

    readonly property int barHeight:    50
    readonly property int moduleRadius: 8
    readonly property int moduleHeight: 16
    readonly property int popupRadius:  12
    readonly property int popupPad:     12
    readonly property int popupWidth:   320

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
}
