// AUTOGENERATED by generate_theme.py
// Source: 02. Abyssal Wave.png
// Edit this file directly or re-run the script.
import QtQuick

QtObject {
    readonly property color bgDark:      "#1a232a"
    readonly property color bgBar:       "#7f1a232a"
    readonly property color bgPopup:     "#222d36"
    readonly property color bgPopupBlur: "#b21a232a"
    readonly property color text:        "#c3c4c5"
    readonly property color textBright:  "#f7f7f7"
    readonly property color textMuted:   "#8d9faf"
    readonly property color border:      "#66455768"
    readonly property color hover:       "#6886a0"
    readonly property color active:      "#b2c2d1"
    readonly property color activeText:  "#252627"
    readonly property color empty:       "#43576a"
    readonly property color warn:        "#d09caa"
    readonly property color green:       "#78c293"

    // Wallpaper picker semantic aliases
    readonly property color base:     "#1a232a"
    readonly property color mantle:   "#222d36"
    readonly property color surface1: "#43576a"
    readonly property color surface2: "#6886a0"

    readonly property int barHeight:    50
    readonly property int moduleRadius: 8
    readonly property int moduleHeight: 16
    readonly property int popupRadius:  12
    readonly property int popupPad:     12
    readonly property int popupWidth:   320

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
}
