// AUTOGENERATED by generate_theme.py
// Source: b-256.jpg
// Edit this file directly or re-run the script.
import QtQuick

QtObject {
    readonly property color bgDark:      "#040333"
    readonly property color bgBar:       "#7f040333"
    readonly property color bgPopup:     "#070541"
    readonly property color bgPopupBlur: "#b2040333"
    readonly property color text:        "#c2c2c6"
    readonly property color textBright:  "#f7f7f7"
    readonly property color textMuted:   "#817fbc"
    readonly property color border:      "#66393775"
    readonly property color hover:       "#5653b6"
    readonly property color active:      "#a8a6dd"
    readonly property color activeText:  "#242427"
    readonly property color empty:       "#353379"
    readonly property color warn:        "#d09caa"
    readonly property color green:       "#78c293"

    // Wallpaper picker semantic aliases
    readonly property color base:     "#040333"
    readonly property color mantle:   "#070541"
    readonly property color surface1: "#353379"
    readonly property color surface2: "#5653b6"

    readonly property int barHeight:    50
    readonly property int moduleRadius: 8
    readonly property int moduleHeight: 16
    readonly property int popupRadius:  12
    readonly property int popupPad:     12
    readonly property int popupWidth:   320

    readonly property string fontFamily: "JetBrainsMono Nerd Font"
}
