// AUTOGENERATED by generate_theme.py
// This file is used by the lock screen (LockSurface.qml)
import QtQuick

QtObject {
    readonly property color bgDark:      "#2c1619"
    readonly property color bgPopup:     "#391c20"
    readonly property color bgPopupBlur: "#b22c1619"
    readonly property color text:        "#c6c2c2"
    readonly property color textBright:  "#f7f7f7"
    readonly property color textMuted:   "#bc7f88"
    readonly property color border:      "#66753741"
    readonly property color hover:       "#b65362"
    readonly property color active:      "#dda6ae"
    readonly property color activeText:  "#272425"
    readonly property color warn:        "#d09caa"
    readonly property color green:       "#78c293"
    readonly property string fontFamily: "JetBrainsMono Nerd Font"
}
