general {
    lock_cmd = pgrep -f "lockscreen/shell.qml" > /dev/null 2>&1 || /home/mert/.config/quickshell/lockscreen/lock.sh
    before_sleep_cmd = loginctl lock-session    # Uyumadan hemen önce ekranı kilitle
    after_sleep_cmd = hyprctl dispatch dpms on  # Uyanınca ekranı aç
}

# 5 dakika (300 saniye) hareketsiz kalınca ekranı kilitle
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5.5 dakika (330 saniye) kalınca monitörü tamamen kapat
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

